[package]
name = "slatedb-py"
description = "A Python binding for SlateDB"
publish = false
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true

[lib]
name = "slatedb"
crate-type = ["cdylib"]
doc = false

[dependencies]
pyo3 = { version = "0.25.1" }
pyo3-async-runtimes = { version = "0.25.0", features = ["tokio-runtime"] }
slatedb = { path = "../slatedb" }
once_cell = "1.19"
tokio = { version = "1.40.0", features = ["fs", "macros", "sync", "rt", "rt-multi-thread", "signal"] }

# Can't directly depend on pyo3 due to:
#
# - https://github.com/PyO3/pyo3/issues/2521
# - https://github.com/PyO3/pyo3/issues/340
#
# Work around this using:
# 
# https://github.com/PyO3/pyo3/blob/main/guide/src/faq.md#i-cant-run-cargo-test-or-i-cant-build-in-a-cargo-workspace-im-having-linker-issues-like-symbol-not-found-or-undefined-reference-to-_pyexc_systemerror
[features]
extension-module = ["pyo3/extension-module"]